# Configuration file for Jekyll
title: Desa Wisata Sigaol Simbolon
description: >-
  Desa wisata yang kaya akan budaya batak, keindahan alam danau toba,
  agrowisata nenas khas Sigaol Simbolon.
baseurl: ""
url: "https://desasigaolsimbolon.github.io"

plugins:
  - jekyll-feed

markdown: kramdown
